name: Unit Tests

on: [push, pull_request]

jobs:
  tests:
    defaults:
      run:
        working-directory: ./dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: "Set up environment"
        run: docker compose -f ./docker-compose.yml up -d --wait
      - name: Run tests
        run: yarn run test
